name: Make videos
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: narakeet/build-video-github-action@v1.0.5
      id: video
      with:
        source-path: script/script.md
        github-token: ${{ secrets.GITHUB_TOKEN }}
        api-key: ${{ secrets.API_KEY }}
    - uses: actions/upload-artifact@v4
      with:
        name: video
        path: "${{ steps.video.outputs.video-file }}" 
